In [ ]:
import statsmodels.api as sm
import numpy as np
import FracRegressionEstimation
import pandas as pd

In [ ]:
# generate test data 
np.random.seed(0)
n = 1000
X = np.random.rand(n, 3) # 3 features
beta_true = np.array([[0.5], [1.0], [-0.5]])  # true coefficients
y = np.maximum(np.minimum(1 / (1 + np.exp(-X @ beta_true))  + np.random.normal(0, 0.4, size=(n, 1)),1),0)


# create an instance of the estimator and fit the model
estimator = FracRegressionEstimation().fit(X,y)
estimator.beta_

AttributeError: module 'frac_regr' has no attribute 'FracRegressionEstimation'

In [ ]:
pd.DataFrame(y).describe()

                 0
count  1000.000000
mean      0.572357
std       0.320539
min       0.000000
25%       0.319685
50%       0.584026
75%       0.865286
max       1.000000

In [ ]:
logistica = sm.Logit(y,X)
logistica.fit().summary() # è proprio la Fractional che fa schifo..... algoritmo converge a quanto fa il 
                          # pacchetto

Optimization terminated successfully.
         Current function value: 0.670159
         Iterations 4

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                 1000
Model:                          Logit   Df Residuals:                      997
Method:                           MLE   Df Model:                            2
Date:                Mon, 30 Mar 2026   Pseudo R-squ.:               -0.002455
Time:                        21:47:34   Log-Likelihood:                -670.16
converged:                       True   LL-Null:                       -668.52
Covariance Type:            nonrobust   LLR p-value:                     1.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1958      0.185      1.056      0.291      -0.168       0.559
x2             0.6844      0.188      3.643      0.000       0.316       1.053
x3            -0.3465      0.191     -1.815      0.069      -0.721       0.028
==============================================================================
"""

In [ ]:
pd.DataFrame(y).describe()

                 0
count  1000.000000
mean      0.611925
std       0.122093
min       0.244552
25%       0.529399
50%       0.612577
75%       0.699358
max       1.000000